# Generated by Django 5.0.4 on 2026-04-27 02:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=64)),
                ('instance_id', models.CharField(max_length=128)),
                ('pubkey_fp', models.CharField(max_length=128)),
                ('hardware_fp', models.CharField(max_length=128)),
                ('schema_version', models.IntegerField()),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('license', models.ForeignKey(blank=True, db_column='license_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenses.license')),
            ],
            options={
                'db_table': 'activations_cloud_id',
                'indexes': [models.Index(fields=['product_code', 'instance_id', 'hardware_fp'], name='activations_product_4a829b_idx')],
                'unique_together': {('product_code', 'instance_id', 'hardware_fp')},
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reported_at', models.DateTimeField()),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_version', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('mismatch', 'mismatch'), ('expired', 'expired'), ('revoked', 'revoked')], max_length=16)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('license', models.ForeignKey(db_column='license_id', on_delete=django.db.models.deletion.CASCADE, to='licenses.license')),
            ],
            options={
                'db_table': 'activations_heartbeat',
                'indexes': [models.Index(fields=['license', '-reported_at'], name='activations_license_456c13_idx')],
            },
        ),
    ]
