# pg_hba.conf — License Console
# 仅允许容器网络与本机；密码使用 scram-sha-256。

# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# 容器内部网络（默认 docker 桥接 172.16.0.0/12）
host    license         license_app     172.16.0.0/12           scram-sha-256
host    license         license_owner   172.16.0.0/12           scram-sha-256
host    license         license_ro      172.16.0.0/12           scram-sha-256

# 复制流（V2 启用主从时打开）
# host    replication     replicator      172.16.0.0/12           scram-sha-256
