# Generated by Django 5.0.4 on 2026-04-27 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prev_hash', models.BinaryField()),
                ('hash', models.BinaryField(unique=True)),
                ('signature', models.BinaryField()),
                ('signature_kid', models.CharField(max_length=64)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_kind', models.CharField(max_length=32)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('target_kind', models.CharField(blank=True, max_length=32, null=True)),
                ('target_id', models.CharField(blank=True, max_length=128, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['-ts'], name='audit_event_ts_ca9af8_idx'), models.Index(fields=['action', '-ts'], name='audit_event_action_c17122_idx')],
            },
        ),
    ]
