# Generated by Django 5.0.4 on 2026-04-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
