{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forge.componentName" (dict "root" . "component" "web") }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "forge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "forge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        {{- include "forge.podExtraLabels" . | nindent 8 }}
    spec:
      {{- if .Values.web.serviceAccountName }}
      serviceAccountName: {{ .Values.web.serviceAccountName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "forge.podSecurityContext" .) }}
      securityContext:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "forge.image" (dict "root" . "component" "web") }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with (include "forge.containerSecurityContext" .) }}
          securityContext:
            {{- . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "forge.fullname" . }}-config
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
