# Generated by Django 5.0.4 on 2026-04-27 02:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_id', models.CharField(max_length=64, unique=True)),
                ('cloud_id_binding', models.BinaryField()),
                ('cloud_id_text', models.TextField()),
                ('hardware_fp_hash', models.BinaryField()),
                ('instance_pubkey', models.BinaryField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('issued', 'issued'), ('active', 'active'), ('expired', 'expired'), ('grace', 'grace'), ('revoked', 'revoked'), ('sunset', 'sunset')], default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('signature', models.BinaryField(blank=True, null=True)),
                ('signature_algo', models.CharField(default='ed25519', max_length=32)),
                ('signature_kid', models.CharField(default='', max_length=64)),
                ('payload_canonical', models.BinaryField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('issued_by', models.ForeignKey(db_column='issued_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'licenses_license',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='licenses_li_custome_73bed9_idx'), models.Index(fields=['product', 'status'], name='licenses_li_product_708cf9_idx'), models.Index(fields=['expires_at'], name='licenses_li_expires_2124f9_idx'), models.Index(fields=['license_id'], name='licenses_li_license_f8b695_idx')],
            },
        ),
    ]
